// ... (existing code skipping much lines for brevity)

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n1',
    userId: 'u1',
    title: 'Payment Successful',
    description: 'Your payment for the Serengeti Migration Safari has been confirmed.',
    type: 'success',
    timestamp: '2026-04-24 09:00',
    isRead: false,
    actionLabel: 'View Booking',
    actionUrl: '/bookings',
  },
  {
    id: 'n2',
    userId: 'u1',
    title: 'New Message from Kofi',
    description: 'Your guide has sent you a message regarding your upcoming trip.',
    type: 'update',
    timestamp: '2026-04-24 10:15',
    isRead: false,
    actionLabel: 'Reply',
    actionUrl: '/messages',
  },
  {
    id: 'n5',
    userId: 'u1',
    title: 'Experience Request Accepted',
    description: 'Zanzibar Retreats has accepted your stay request for the Blue Mountains hike.',
    type: 'success',
    timestamp: '2026-04-24 11:30',
    isRead: false,
  },
  {
    id: 'n3',
    userId: 'u1',
    title: 'Driver Assigned',
    description: 'Samuel Okoro has been assigned as your driver for the airport pickup.',
    type: 'update',
    timestamp: '2026-04-23 15:30',
    isRead: true,
  },
  {
    id: 'n6',
    userId: 'u1',
    title: 'Security Alert',
    description: 'A new login was detected on your account from a new device in Lagos, Nigeria.',
    type: 'warning',
    timestamp: '2026-04-23 18:45',
    isRead: true,
    actionLabel: 'Review Activity',
  },
  {
    id: 'n4',
    userId: 'u1',
    title: 'Profile Under Review',
    description: 'Your driver onboarding request is currently being reviewed by our team.',
    type: 'update',
    timestamp: '2026-04-22 11:20',
    isRead: true,
  },
  {
    id: 'n7',
    userId: 'u1',
    title: 'Dispute Resolved',
    description: 'The dispute regarding your canceled ride #rr1 has been resolved in your favor.',
    type: 'success',
    timestamp: '2026-04-21 09:12',
    isRead: true,
    actionLabel: 'View Details',
  },
];

// ... (previous MOCK_SPECIALISTS definition)

export const MOCK_TICKETS = [
  {
    id: 't1',
    userId: 'u1',
    category: 'Booking',
    subject: 'Change of Date for Safari',
    description: 'I would like to change my safari date from June 12 to June 15.',
    status: 'In Progress',
    createdAt: '2026-04-20 10:00',
    updatedAt: '2026-04-21 14:00',
  },
  {
    id: 'd1',
    userId: 'u1',
    category: 'Dispute',
    subject: 'Refund Request for Canceled Ride',
    description: 'The driver did not show up, and I was charged.',
    status: 'Escalated',
    createdAt: '2026-04-18 09:00',
    updatedAt: '2026-04-19 11:00',
    isDispute: true,
    relatedId: 'r1',
  },
];

export const MOCK_RIDE_REQUESTS = [
  {
    id: 'rr1',
    passengerName: 'Mark Ochieng',
    pickupLocation: 'Kilimanjaro Airport',
    destination: 'Moshi Center',
    paxCount: 4,
    status: 'Pending',
    price: 45000,
    currency: 'TZS',
    time: '2026-04-25 14:30',
    isRoundTrip: false,
  },
  {
    id: 'rr2',
    passengerName: 'Grace Mbeki',
    pickupLocation: 'Arusha Clock Tower',
    destination: 'Serena Forest Lodge',
    paxCount: 2,
    status: 'Accepted',
    price: 65000,
    currency: 'TZS',
    time: '2026-04-24 16:00',
    isRoundTrip: true,
  },
];

export const MOCK_TRIPS = [
  {
    id: '100',
    title: 'Kilimanjaro Luxury Summit Expedition',
    location: { city: 'Moshi', country: 'Tanzania' },
    duration: '7 Days',
    difficulty: 'Expert',
    groupType: 'Private',
    price: { local: 8500000, currency: 'TZS', usd: 3200 },
    rating: 5.0,
    reviewCount: 45,
    coverImage: 'https://picsum.photos/seed/kili/800/600',
    experienceType: 'Adventure',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Good',
    isSponsored: true,
    startDate: '2026-08-23T08:00:00Z',
    endDate: '2026-08-29T18:00:00Z',
    bookingDeadline: '2026-08-15T23:59:59Z',
    requiredEquipment: ['Warm Parka', 'Sturdy Hiking Boots', 'Headlamp', 'Gloves'],
    activities: [
      { id: 'a1', name: 'Peak Climb', description: 'Reaching the summit at dawn' },
      { id: 'a2', name: 'Glacier Walk', description: 'Guided walk across ancient ice' },
    ],

    rides: [
      {
        id: 'r1',
        type: 'Bus',
        make: 'Isuzu',
        model: 'FTR',
        color: 'White',
        plateNumber: 'TZ 777 BUS',
        picture:
          'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=400',
        driverName: 'Zuberi Bakari',
        rating: 4.9,
        price: 800,
        currency: 'USD',
        capacity: 30,
      },
      {
        id: 'r2',
        type: 'Safari Van',
        make: 'Toyota',
        model: 'Hiace',
        color: 'Beige',
        plateNumber: 'TZ 888 VAN',
        picture:
          'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&q=80&w=400',
        driverName: 'Juma Bakari',
        rating: 4.9,
        price: 150,
        currency: 'USD',
        capacity: 8,
      },
    ],

    accommodations: [
      {
        id: 'h1',
        name: 'Mount Meru Game Lodge',
        type: 'Hotel',
        images: ['https://picsum.photos/seed/hotel1/400/300'],
        reviews: 150,
        rating: 4.8,
        pricePerNight: 250,
        currency: 'USD',
        maxGuests: 2,
        bedsLeft: 12,
      },
      {
        id: 'h2',
        name: 'Kilimanjaro Dormitory',
        type: 'Camp',
        images: ['https://picsum.photos/seed/dorm/400/300'],
        reviews: 45,
        rating: 4.2,
        pricePerNight: 30,
        currency: 'USD',
        maxGuests: 12,
        bedsLeft: 8,
      },
    ],
  },
  {
    id: '1',
    title: 'Serengeti Migration Safari',
    location: { city: 'Arusha', country: 'Tanzania' },
    duration: '5 Days',
    difficulty: 'Easy',
    groupType: 'Shared',
    price: { local: 1500000, currency: 'TZS', usd: 600 },
    rating: 4.9,
    reviewCount: 124,
    coverImage: 'https://picsum.photos/seed/safari1/800/600',
    experienceType: 'Excursion',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Medium',
    startDate: '2026-06-12T09:00:00Z',
    endDate: '2026-06-16T17:00:00Z',
    bookingDeadline: '2026-06-05T20:00:00Z',
    requiredEquipment: ['Binoculars', 'Sunscreen', 'Hat', 'Camera'],
    activities: [
      { id: 'a3', name: 'Game Drive', description: 'Early morning animal spotting' },
      {
        id: 'a4',
        name: 'Photography',
        description: 'Workshop with professional wildlife photographer',
      },
    ],

    rides: [
      {
        id: 'r3',
        type: 'Safari Van',
        make: 'Nissan',
        model: 'Urvan',
        color: 'Green',
        plateNumber: 'TZ 999 SAF',
        picture:
          'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=400',
        driverName: 'Emma Omollo',
        rating: 4.7,
        price: 120,
        currency: 'USD',
        capacity: 6,
      },
      {
        id: 'r4',
        type: 'Car',
        make: 'Toyota',
        model: 'Rav4',
        color: 'Silver',
        plateNumber: 'TZ 111 CAR',
        picture:
          'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=400',
        driverName: 'David Kojo',
        rating: 4.5,
        price: 50,
        currency: 'USD',
        capacity: 4,
      },
    ],

    accommodations: [
      {
        id: 'h3',
        name: 'Serengeti Luxury Camp',
        type: 'Camp',
        images: ['https://picsum.photos/seed/camp1/400/300'],
        reviews: 80,
        rating: 4.6,
        pricePerNight: 120,
        currency: 'USD',
        maxGuests: 4,
        bedsLeft: 16,
      },
      {
        id: 'h4',
        name: 'Savannah Short Let',
        type: 'Short Let',
        images: ['https://picsum.photos/seed/sl/400/300'],
        reviews: 12,
        rating: 4.9,
        pricePerNight: 85,
        currency: 'USD',
        maxGuests: 2,
        bedsLeft: 4,
      },
      {
        id: 'h5',
        name: 'Arusha City Hotel',
        type: 'Hotel',
        images: ['https://picsum.photos/seed/hotelcity/400/300'],
        reviews: 200,
        rating: 4.4,
        pricePerNight: 150,
        currency: 'USD',
        maxGuests: 2,
        bedsLeft: 20,
      },
    ],
  },
  {
    id: '2',
    title: 'Blue Mountains Cultural Hike',
    location: { city: 'Kingston', country: 'Jamaica' },
    duration: '1 Day',
    difficulty: 'Moderate',
    groupType: 'Private',
    price: { local: 25000, currency: 'JMD', usd: 160 },
    rating: 4.8,
    reviewCount: 89,
    coverImage: 'https://picsum.photos/seed/hiking1/800/600',
    experienceType: 'Hiking',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Low',
    requiredEquipment: ['Hiking Shoes', 'Water Bottle', 'Backpack'],
  },
  {
    id: '3',
    title: 'Zanzibar Spice Tour & Beach Relax',
    location: { city: 'Stone Town', country: 'Tanzania' },
    duration: '3 Days',
    difficulty: 'Easy',
    groupType: 'Shared',
    price: { local: 800000, currency: 'TZS', usd: 320 },
    rating: 4.7,
    reviewCount: 210,
    coverImage: 'https://picsum.photos/seed/beach1/800/600',
    experienceType: 'Beach',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Good',
    requiredEquipment: ['Swimwear', 'Sunglasses', 'Towel'],
  },
  {
    id: '4',
    title: 'Ngorongoro Crater Day Trip',
    location: { city: 'Karatu', country: 'Tanzania' },
    duration: '1 Day',
    difficulty: 'Easy',
    groupType: 'Shared',
    price: { local: 450000, currency: 'TZS', usd: 180 },
    rating: 4.8,
    reviewCount: 320,
    coverImage: 'https://picsum.photos/seed/crater/800/600',
    experienceType: 'Excursion',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Good',
    requiredEquipment: ['Binoculars', 'Warm Jacket'],
    accommodations: [
      {
        id: 'h6',
        name: 'Ngorongoro Farmhouse',
        type: 'Lodge',
        images: ['https://picsum.photos/seed/lodge1/400/300'],
        reviews: 95,
        rating: 4.7,
        pricePerNight: 180,
        currency: 'USD',
        maxGuests: 2,
        bedsLeft: 5,
      },
    ],
  },
  {
    id: '5',
    title: 'Bagamoyo History & Culture',
    location: { city: 'Bagamoyo', country: 'Tanzania' },
    duration: '1 Day',
    difficulty: 'Easy',
    groupType: 'Private',
    price: { local: 150000, currency: 'TZS', usd: 60 },
    rating: 4.6,
    reviewCount: 54,
    coverImage: 'https://picsum.photos/seed/history/800/600',
    experienceType: 'Cultural',
    isVerified: true,
    hasEmergencyPlan: false,
    networkStatus: 'Medium',
    requiredEquipment: ['Walking shoes', 'Sunscreen'],
  },
  {
    id: '6',
    title: 'Simien Mountains High Altitude Trek',
    location: { city: 'Debark', country: 'Ethiopia' },
    duration: '6 Days',
    difficulty: 'Expert',
    groupType: 'Private',
    price: { local: 1200000, currency: 'ETB', usd: 400 },
    rating: 4.9,
    reviewCount: 78,
    coverImage: 'https://picsum.photos/seed/simien/800/600',
    experienceType: 'Hiking',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Low',
    requiredEquipment: ['Thermal layers', 'Hiking poles'],
  },
  {
    id: '7',
    title: 'Lalibela Rock-Hewn Churches Tour',
    location: { city: 'Lalibela', country: 'Ethiopia' },
    duration: '2 Days',
    difficulty: 'Easy',
    groupType: 'Shared',
    price: { local: 450000, currency: 'ETB', usd: 150 },
    rating: 5.0,
    reviewCount: 156,
    coverImage: 'https://picsum.photos/seed/lalibela/800/600',
    experienceType: 'Pilgrimage',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Medium',
    requiredEquipment: ['Scarf for church entry', 'Socks'],
  },
  {
    id: '8',
    title: 'Masai Mara Bush Walk',
    location: { city: 'Narok', country: 'Kenya' },
    duration: '3 Days',
    difficulty: 'Moderate',
    groupType: 'Shared',
    price: { local: 45000, currency: 'KES', usd: 350 },
    rating: 4.8,
    reviewCount: 92,
    coverImage: 'https://picsum.photos/seed/mara/800/600',
    experienceType: 'Adventure',
    isVerified: true,
    hasEmergencyPlan: true,
    networkStatus: 'Medium',
    requiredEquipment: ['Good walking shoes', 'Hat'],
  },
];

export const MOCK_WISHLIST = [
  { tripId: '1', expiryDate: '2026-05-15' },
  { tripId: '2', expiryDate: '2026-06-01' },
];

export const MOCK_MESSAGES = [
  {
    id: 'm1',
    senderId: 'g1',
    text: 'Hello! Are you ready for your safari tomorrow?',
    timestamp: '10:00 AM',
    isMe: false,
  },
  {
    id: 'm2',
    senderId: 'u1',
    text: 'Yes, very excited! What should I bring?',
    timestamp: '10:05 AM',
    isMe: true,
  },
  {
    id: 'm3',
    senderId: 'g1',
    text: 'Just your camera and some sunscreen. I will handle the rest!',
    timestamp: '10:10 AM',
    isMe: false,
  },
];

export const MOCK_SPECIALISTS = [
  {
    id: 'g1',
    type: 'Individual',
    name: 'Kofi Mensah',
    profilePhoto: 'https://picsum.photos/seed/kofi/200/200',
    description:
      'Expert safari guide with 10+ years exploring the East African wilderness. Specialized in big cat tracking and cultural birding. Committed to providing authentic, safe, and deeply informative adventures.',
    specialization: ['Safari', 'Adventure'],
    location: 'Nairobi, Kenya',
    rating: 4.95,
    completedTrips: 450,
    responseTime: '< 30 mins',
    isVerified: true,
    isCertificationVerified: true,
    activeExperienceIds: ['1', '100'],
    availability: {
      blockedDates: ['2026-06-10', '2026-06-15'],
      blockedHours: ['2026-06-12T10:00', '2026-06-12T11:00'],
    },
    reviews: [
      {
        id: 'rev1',
        userName: 'Alice J.',
        userPhoto: 'https://picsum.photos/seed/u1/100/100',
        rating: 5,
        comment: 'Kofi is an absolute legend! Best safari ever.',
        date: 'Oct 23, 2025',
        timestamp: 1729683000000,
        tripId: '1',
        bookingId: 'b1',
        reply: {
          text: 'Thank you Alice! It was a pleasure hosting you.',
          date: 'Oct 24, 2025',
          timestamp: 1729760400000,
          authorName: 'Kofi Mensah',
          authorPhoto: 'https://picsum.photos/seed/kofi/200/200',
          authorRole: 'Guide'
        }
      },
      {
        id: 'rev2',
        userName: 'Bob M.',
        userPhoto: 'https://picsum.photos/seed/u2/100/100',
        rating: 4,
        comment: 'Great knowledge of local trails.',
        date: 'Nov 12, 2025',
        timestamp: 1731422700000,
        tripId: '100'
      }
    ],
  },
  {
    id: 'a1',
    type: 'Agency',
    name: 'Roots & Routes Africa',
    description:
      'Expert local guides across West Africa since 2012. We specialize in heritage tours, eco-adventures, and large group cultural immersions. Your bridge to authentic African encounters.',
    profilePhoto: 'https://picsum.photos/seed/agency1/200/300',
    specialization: ['Cultural', 'Adventure'],
    location: 'Accra, Ghana',
    rating: 4.9,
    completedTrips: 1200,
    responseTime: '< 15 mins',
    isVerified: true,
    isCertificationVerified: true,
    memberCount: 15,
    members: ['g1', 'g2'],
    activeExperienceIds: ['2'],
    availability: {
      blockedDates: ['2026-07-01', '2026-07-02'],
      blockedHours: [],
    },
    reviews: [
      {
        id: 'rev3',
        userName: 'Chris L.',
        userPhoto: 'https://picsum.photos/seed/u3/100/100',
        rating: 5,
        comment: 'Very professional agency. Handled our group of 30 students perfectly.',
        date: 'Jan 2026',
        timestamp: 1735689600000
      },
    ],
  },
  {
    id: 'g2',
    type: 'Individual',
    name: 'Sarah Williams',
    description:
      "Passionate about Accra's vibrant history and hidden culinary gems. I offer intimate, storyteller-style city tours that take you beyond the postcards.",
    profilePhoto: 'https://picsum.photos/seed/sarah/200/200',
    specialization: ['Cultural', 'City Tour'],
    location: 'Accra, Ghana',
    rating: 4.88,
    completedTrips: 320,
    responseTime: '< 1 hour',
    isVerified: true,
    isCertificationVerified: true,
    activeExperienceIds: ['3'],
    availability: {
      blockedDates: ['2026-08-15'],
      blockedHours: [],
    },
    reviews: [
      {
        id: 'rev4',
        userName: 'Diana P.',
        userPhoto: 'https://picsum.photos/seed/u4/100/100',
        rating: 5,
        comment: 'Sarah knows Accra like the back of her hand.',
        date: 'Dec 2025',
        timestamp: 1732924800000
      },
    ],
  },
];

export const MOCK_PRIVATE_REQUESTS = [
  {
    id: 'pr1',
    travelerId: 'u1',
    guideId: 'g1',
    title: 'Custom Serengeti Photography',
    type: 'Safari',
    location: 'Tanzania',
    description:
      'Looking for a private session focused on capturing the big five during golden hour.',
    participants: 2,
    accommodationType: 'Luxury Camp',
    transportType: '4x4 Safari Vehicle',
    foodInclusive: true,
    requestedDate: '2026-06-25',
    status: 'Pending',
  },
];

export const MOCK_CHAT_PREVIEWS = [
  {
    id: 'c1',
    participantId: 'g1',
    participantName: 'Kofi Mensah',
    participantPhoto: 'https://picsum.photos/seed/kofi/100/100',
    participantRole: 'Guide',
    lastMessage: 'I have prepared the safari gear for tomorrow.',
    timestamp: '10:10 AM',
    unreadCount: 0,
  },
  {
    id: 'c2',
    participantId: 'd1',
    participantName: 'Samuel Okoro',
    participantPhoto: 'https://picsum.photos/seed/d1/100/100',
    participantRole: 'Driver',
    lastMessage: 'Where exactly should I pick you up from?',
    timestamp: 'Yesterday',
    unreadCount: 1,
  },
  {
    id: 'c3',
    participantId: 's1',
    participantName: 'Zanzibar Retreats',
    participantPhoto: 'https://picsum.photos/seed/agency1/100/100',
    participantRole: 'StayProvider',
    lastMessage: 'Your room at the West Park Hotels is ready.',
    timestamp: '2 days ago',
    unreadCount: 0,
  },
];

export const MOCK_BOOKINGS = [
  {
    id: 'b1',
    tripId: '1',
    userId: 'u1',
    status: 'Active',
    totalPaid: 1500000,
    currency: 'TZS',
    startDate: '2026-04-20',
    endDate: '2026-04-25',
    fulfillment: [
      { service: 'Ride', isFulfilled: true, providerId: 'd1', providerName: 'Samuel Okoro' },
      { service: 'Stay', isFulfilled: true, providerId: 'h1', providerName: 'West Park Hotels' },
      { service: 'Experience', isFulfilled: false, providerId: 'g1', providerName: 'Kofi Mensah' },
    ],
  },
  {
    id: 'b_past1',
    tripId: '3',
    userId: 'u1',
    status: 'Completed',
    totalPaid: 800000,
    currency: 'TZS',
    startDate: '2025-12-10',
    endDate: '2025-12-13',
    fulfillment: [
      { service: 'Experience', isFulfilled: true, providerId: 'g1', providerName: 'Kofi Mensah' }
    ]
  },
  {
    id: 'b_past2',
    tripId: '4',
    userId: 'u2',
    status: 'Completed',
    totalPaid: 450000,
    currency: 'TZS',
    startDate: '2026-01-05',
    endDate: '2026-01-05',
    fulfillment: [
      { service: 'Experience', isFulfilled: true, providerId: 'g1', providerName: 'Kofi Mensah' }
    ],
    rideDetails: {
      driverId: 'd1',
      pickupLocation: 'Kilimanjaro Airport',
      pickupTime: '14:30',
    },
    stayDetails: [{ stayId: 'h1', rooms: [{ tier: 'Luxury', count: 2 }] }],
  },
  {
    id: 'b2',
    tripId: '100',
    userId: 'u1',
    status: 'Upcoming',
    totalPaid: 8500000,
    currency: 'TZS',
    startDate: '2026-08-23',
    endDate: '2026-08-29',
    fulfillment: [
      { service: 'Ride', isFulfilled: false, providerId: 'd2', providerName: 'Grace Mbeki' },
      {
        service: 'Stay',
        isFulfilled: false,
        providerId: 'h3',
        providerName: 'Serengeti Luxury Camp',
      },
      { service: 'Experience', isFulfilled: false, providerId: 'g1', providerName: 'Kofi Mensah' },
    ],
  },
];

export const MOCK_DRIVERS = [
  {
    id: 'd1',
    name: 'Samuel Okoro',
    photo: 'https://picsum.photos/seed/d1/200/200',
    rating: 4.8,
    vehicle: {
      type: 'Safari Van',
      make: 'Toyota',
      model: 'Land Cruiser',
      color: 'White',
      plateNumber: 'TZ 123 ABC',
      picture:
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=400',
      maxPassengers: 8,
      isFleetOwned: false,
      status: 'Approved',
    },
    settings: { pricePerKm: 1500, waitingFeePerHour: 5000, acceptsRoundTrip: true },
  },
  {
    id: 'd2',
    name: 'Grace Mbeki',
    photo: 'https://picsum.photos/seed/d2/200/200',
    rating: 4.9,
    vehicle: {
      type: 'Car',
      make: 'Honda',
      model: 'Civic',
      color: 'Silver',
      plateNumber: 'TZ 456 DEF',
      picture:
        'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=400',
      maxPassengers: 4,
      isFleetOwned: true,
      companyName: 'Swift Rides',
      status: 'Approved',
    },
    settings: { pricePerKm: 1200, waitingFeePerHour: 3000, acceptsRoundTrip: true },
  },
  {
    id: 'd3',
    name: 'David Kamau',
    photo: 'https://picsum.photos/seed/d3/200/200',
    rating: 4.7,
    vehicle: {
      type: 'SUV',
      make: 'Land Rover',
      model: 'Defender',
      color: 'Black',
      plateNumber: 'TZ 789 GHI',
      picture:
        'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=400',
      maxPassengers: 6,
      isFleetOwned: false,
      status: 'Approved',
    },
    settings: { pricePerKm: 2000, waitingFeePerHour: 6000, acceptsRoundTrip: false },
  },
  {
    id: 'd4',
    name: 'Aisha Juma',
    photo: 'https://picsum.photos/seed/d4/200/200',
    rating: 5.0,
    vehicle: {
      type: 'Car',
      make: 'Toyota',
      model: 'Camry',
      color: 'Gold',
      plateNumber: 'TZ 012 JKL',
      picture:
        'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=400',
      maxPassengers: 4,
      isFleetOwned: false,
      status: 'Approved',
    },
    settings: { pricePerKm: 1300, waitingFeePerHour: 4000, acceptsRoundTrip: true },
  },
];
